import {
  Activity,
  Braces,
  Bug,
  FileDown,
  FileUp,
  GripHorizontal,
  Lock,
  LockOpen,
  PanelRightClose,
  PictureInPicture2,
  Scaling,
  AlignCenterHorizontal,
  AlignCenterVertical,
  AlignEndHorizontal,
  AlignEndVertical,
  AlignHorizontalDistributeCenter,
  AlignStartHorizontal,
  AlignStartVertical,
  AlignVerticalDistributeCenter,
  ArrowDownToLine,
  ArrowUpToLine,
  BookOpen,
  Box,
  Cable,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsRight,
  CircleCheck,
  CircleHelp,
  CircleDot,
  CircleX,
  ClipboardPaste,
  Clock,
  Code,
  Command,
  Copy,
  CopyPlus,
  Cpu,
  Crosshair,
  Disc3,
  Droplets,
  Ellipsis,
  Eraser,
  Eye,
  EyeOff,
  FilePlus2,
  Flame,
  Footprints,
  FlipHorizontal2,
  FolderOpen,
  Gamepad2,
  Gauge,
  Grid3x3,
  Hammer,
  Hand,
  History,
  House,
  Info,
  Keyboard,
  Languages,
  Lightbulb,
  Magnet,
  Maximize,
  Microchip,
  Minus,
  Moon,
  Package,
  Palette,
  PanelBottom,
  PanelLeft,
  PanelRight,
  Pause,
  Pencil,
  Play,
  Plus,
  Radio,
  Redo2,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Route,
  Ruler,
  Save,
  Scissors,
  Search,
  Send,
  Settings,
  Sparkles,
  Square,
  SquareTerminal,
  Star,
  StepForward,
  Sun,
  Tag,
  Target,
  Thermometer,
  Trash2,
  TriangleAlert,
  Undo2,
  Volume2,
  Waves,
  Wind,
  Wrench,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
  ImageDown,
  Type,
  MoveUpRight,
  SquareDashed,
  Map as MapIcon,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  'align-left': AlignStartVertical,
  'align-center': AlignCenterVertical,
  'align-right': AlignEndVertical,
  'align-top': AlignStartHorizontal,
  'align-middle': AlignCenterHorizontal,
  'align-bottom': AlignEndHorizontal,
  'dist-h': AlignHorizontalDistributeCenter,
  'dist-v': AlignVerticalDistributeCenter,
  front: ArrowUpToLine,
  back: ArrowDownToLine,
  book: BookOpen,
  box: Box,
  cable: Cable,
  chart: ChartLine,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  check: Check,
  help: CircleHelp,
  ok: CircleCheck,
  probe: CircleDot,
  error: CircleX,
  paste: ClipboardPaste,
  clock: Clock,
  code: Code,
  copy: Copy,
  duplicate: CopyPlus,
  cpu: Cpu,
  crosshair: Crosshair,
  eraser: Eraser,
  new: FilePlus2,
  flip: FlipHorizontal2,
  open: FolderOpen,
  gauge: Gauge,
  grid: Grid3x3,
  build: Hammer,
  info: Info,
  keyboard: Keyboard,
  languages: Languages,
  bulb: Lightbulb,
  magnet: Magnet,
  fit: Maximize,
  chip: Microchip,
  minus: Minus,
  moon: Moon,
  package: Package,
  'panel-bottom': PanelBottom,
  'panel-left': PanelLeft,
  'panel-right': PanelRight,
  pause: Pause,
  play: Play,
  plus: Plus,
  redo: Redo2,
  reset: RefreshCw,
  'rotate-ccw': RotateCcw,
  rotate: RotateCw,
  route: Route,
  save: Save,
  cut: Scissors,
  search: Search,
  send: Send,
  settings: Settings,
  sparkles: Sparkles,
  stop: Square,
  terminal: SquareTerminal,
  star: Star,
  step: StepForward,
  sun: Sun,
  trash: Trash2,
  warning: TriangleAlert,
  undo: Undo2,
  waves: Waves,
  wrench: Wrench,
  x: X,
  zap: Zap,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  image: ImageDown,
  type: Type,
  arrow: MoveUpRight,
  frame: SquareDashed,
  map: MapIcon,
  'chevrons-right': ChevronsRight,
  'palette': Palette,
  'more': Ellipsis,
  'tag': Tag,
  'pencil': Pencil,
  'history': History,
  home: House,
  'command': Command,
  'thermometer': Thermometer,
  'droplets': Droplets,
  'flame': Flame,
  'volume': Volume2,
  'hand': Hand,
  'gamepad': Gamepad2,
  'radio': Radio,
  'eye': Eye,
  'eye-off': EyeOff,
  'target': Target,
  'ruler': Ruler,
  'disc': Disc3,
  footprints: Footprints,
  wind: Wind,
  bug: Bug,
  lock: Lock,
  unlock: LockOpen,
  /** Detach a docked panel into a floating window. */
  float: PictureInPicture2,
  /** Put a floating panel back in its place. */
  dock: PanelRightClose,
  grip: GripHorizontal,
  snippet: Braces,
  'file-down': FileDown,
  'file-up': FileUp,
  scale: Scaling,
};

/** Icons that point along the reading direction: mirrored in right-to-left layouts. */
const DIRECTIONAL = new Set(['chevron-right', 'chevron-left', 'chevrons-right', 'dock']);

export function Icon({ name, size, className, fill }: { name: string; size?: number; className?: string; fill?: string }) {
  const C = ICONS[name] ?? Box;
  const cls = DIRECTIONAL.has(name) ? `${className ?? ''} dir-icon`.trim() : className;
  return <C size={size} className={cls} strokeWidth={1.75} fill={fill ?? 'none'} />;
}
