import {
  Activity,
  AlignCenterHorizontal,
  AlignCenterVertical,
  AlignEndHorizontal,
  AlignEndVertical,
  AlignHorizontalDistributeCenter,
  AlignStartHorizontal,
  AlignStartVertical,
  AlignVerticalDistributeCenter,
  ArrowDownToLine,
  ArrowUpToLine,
  BookOpen,
  Box,
  Cable,
  ChartLine,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  CircleDot,
  CircleX,
  ClipboardPaste,
  Clock,
  Code,
  Copy,
  CopyPlus,
  Cpu,
  Crosshair,
  Eraser,
  FilePlus2,
  FlipHorizontal2,
  FolderOpen,
  Gauge,
  Grid3x3,
  Hammer,
  Info,
  Keyboard,
  Lightbulb,
  Magnet,
  Maximize,
  Microchip,
  Minus,
  Moon,
  Package,
  PanelBottom,
  PanelLeft,
  PanelRight,
  Pause,
  Play,
  Plus,
  Redo2,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Route,
  Save,
  Scissors,
  Search,
  Send,
  Settings,
  Sparkles,
  Square,
  SquareTerminal,
  Star,
  StepForward,
  Sun,
  Trash2,
  TriangleAlert,
  Undo2,
  Waves,
  Wrench,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  'align-left': AlignStartVertical,
  'align-center': AlignCenterVertical,
  'align-right': AlignEndVertical,
  'align-top': AlignStartHorizontal,
  'align-middle': AlignCenterHorizontal,
  'align-bottom': AlignEndHorizontal,
  'dist-h': AlignHorizontalDistributeCenter,
  'dist-v': AlignVerticalDistributeCenter,
  front: ArrowUpToLine,
  back: ArrowDownToLine,
  book: BookOpen,
  box: Box,
  cable: Cable,
  chart: ChartLine,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  ok: CircleCheck,
  probe: CircleDot,
  error: CircleX,
  paste: ClipboardPaste,
  clock: Clock,
  code: Code,
  copy: Copy,
  duplicate: CopyPlus,
  cpu: Cpu,
  crosshair: Crosshair,
  eraser: Eraser,
  new: FilePlus2,
  flip: FlipHorizontal2,
  open: FolderOpen,
  gauge: Gauge,
  grid: Grid3x3,
  build: Hammer,
  info: Info,
  keyboard: Keyboard,
  bulb: Lightbulb,
  magnet: Magnet,
  fit: Maximize,
  chip: Microchip,
  minus: Minus,
  moon: Moon,
  package: Package,
  'panel-bottom': PanelBottom,
  'panel-left': PanelLeft,
  'panel-right': PanelRight,
  pause: Pause,
  play: Play,
  plus: Plus,
  redo: Redo2,
  reset: RefreshCw,
  'rotate-ccw': RotateCcw,
  rotate: RotateCw,
  route: Route,
  save: Save,
  cut: Scissors,
  search: Search,
  send: Send,
  settings: Settings,
  sparkles: Sparkles,
  stop: Square,
  terminal: SquareTerminal,
  star: Star,
  step: StepForward,
  sun: Sun,
  trash: Trash2,
  warning: TriangleAlert,
  undo: Undo2,
  waves: Waves,
  wrench: Wrench,
  x: X,
  zap: Zap,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
};

export function Icon({ name, size, className, fill }: { name: string; size?: number; className?: string; fill?: string }) {
  const C = ICONS[name] ?? Box;
  return <C size={size} className={className} strokeWidth={1.75} fill={fill ?? 'none'} />;
}
